### ISSUE TITLE
Configuring the Smartnode Stack (Docker Mode) Documentation

### ISSUE THREAD

**Issue by CMD10M** [rocket-pool/old.docs.rocketpool.net#103]
Please clearly state to create a new infura 'ETH2' project when setting up a sync checkpoint and that this infura project is different than the 'Ethereum' project used for the fallback execution client. 

![image](https://user-images.githubusercontent.com/100216095/166791558-6975fc7d-dd20-4658-92ca-aa1ffd2dd508.png)

**Comment by jclapis** [comment]
Ok, I'll add some more screenshots to make ETH2 more prominent.
