### ISSUE TITLE
cntrl + C to stop the spamming of new items

### ISSUE THREAD

**Issue by Elevator8-source** [rocket-pool/old.docs.rocketpool.net#107]
https://docs.rocketpool.net/guides/node/starting-rp.html#checking-the-service-status-and-logs

Please list at the bottom of this section that you can exit the spamming of new items with cntrl + C

**Comment by jclapis** [comment]
Sure thing, I added this at the end:
![image](https://user-images.githubusercontent.com/627896/167967813-10fb970c-e189-417d-ab75-347dbffa8a32.png)
