### ISSUE TITLE
Depositing ETH and Creating a Minipool (contains outdated commission fee structure)

### ISSUE THREAD

**Issue by Elevator8-source** [rocket-pool/old.docs.rocketpool.net#108]
[Depositing ETH and Creating a Minipool](https://docs.rocketpool.net/guides/node/create-validator.html#depositing-eth-and-creating-a-minipool)

The system is currently simplified, but the documentation shows the old system.

**Comment by blinc117** [comment]
I will work this into my 1.5.x docs update

**Comment by blinc117** [comment]
Completed - [PR](https://github.com/rocket-pool/docs.rocketpool.net/pull/138)

**Comment by blinc117** [comment]
@jclapis  You can close
