### ISSUE TITLE
Add instructions for `rocketpool node set-voting-delegate`

### ISSUE THREAD

**Issue by blinc117** [rocket-pool/old.docs.rocketpool.net#136]
Add instructions and description to documentation 

- Voting support: the command rocketpool node set-voting-delegate can be used to specify an Ethereum address you would like represent your node when voting on Rocket Pool DAO governance proposals.
  - This should be something you can safely use with a browser.
  - A full write-up of DAO voting, Snapshot, and this command will be released soon.
  
  Introduced in 1.4.2 (Fixed in 1.4.3):
  https://github.com/rocket-pool/smartnode-install/releases/tag/v1.4.2

**Comment by blinc117** [comment]
WIP: 
https://github.com/blinc117/docs.rocketpool.net/tree/1.5-Doc-Upadtes

**Comment by jclapis** [comment]
Resolved with a previous update :+1:
