### ISSUE TITLE
Could not install Rocket Pool service: Could not set executable permissions on package files.

### ISSUE THREAD

**Issue by cnzhang2022** [rocket-pool/old.docs.rocketpool.net#140]
rocketpool service install -d

Skipping steps 1 - 4 (OS dependencies & docker)
Step 5 of 9: Checking for existing installation...
Step 6 of 9: Creating Rocket Pool user data directory...
Step 7 of 9: Downloading Rocket Pool package files...
Step 8 of 9: Copying package files to Rocket Pool user data directory...
Could not install Rocket Pool service: Could not set executable permissions on package files.

why?

**Comment by jclapis** [comment]
Hi! Resolving any installation issues will be much easier if we can talk real time. Please visit the #support channel in our Discord server for help: http://discord.gg/rocketpool
