### ISSUE TITLE
Hybrid mode config doc is missing a section on opening UFW ports

### ISSUE THREAD

**Issue by pieter-astra** [rocket-pool/old.docs.rocketpool.net#42]
The hybrid mode config doc (https://docs.rocketpool.net/guides/node/hybrid.html#setting-up-an-external-eth1-client) is missing a section on opening UFW ports. If you have UFW and don't do that, the RP dockers can't reach your external eth1 and/or eth2 clients.

Taking a page from the grafana docs, you'd first run docker inspect rocketpool_net | grep -Po "(?<=\"Subnet\": \")[0-9./]+" to find the ip (note: you needrocketpool_net instead of rocketpool_monitor-net). In my case this gave 172.18.0.0/16. 

For e.g. Lighthouse and Geth default ports you then need to add the following rules to UFW:
sudo ufw allow from 172.18.0.0/16 to any port 8545 comment "Allow Rocket Pool access to Geth"
sudo ufw allow from 172.18.0.0/16 to any port 5052 comment "Allow Rocket Pool access to Lighthouse beacon"

**Comment by pieter-astra** [comment]
In addition, the docs should point out that you need to use your host machine's local IP in ~/.rocketpool/config.yml and not 0.0.0.0.
( ‘localhost’ or ‘127.0.0.1’ won’t work there either, since those resolve to the internal docker network instead of your host maxchine.)
It needs to be something like 192.168.x.y, ifconfig should show it if you’re unsure.

**Comment by jclapis** [comment]
Updated in https://github.com/rocket-pool/docs.rocketpool.net/commit/4fac85d33b70669fbf3621f8d3a9529a20066c11. Thank you for catching all of this!

**Comment by turboboost55** [comment]
4fac85d adds the necessary info to hybrid.md, but it doesn't seem to be included anywhere in the main guides at https://docs.rocketpool.net/guides, at least not that I could find.  This is critical information that is needed for hybrid operation.
