### ISSUE TITLE
Doco Update

### ISSUE THREAD

**Issue by dietzam** [rocket-pool/old.docs.rocketpool.net#64]
![Screenshot 2021-11-09 215445](https://user-images.githubusercontent.com/8992858/140911726-a0624268-2db2-47a8-882b-0e94a695a8dc.png)

**Comment by blinc117** [comment]
This is now mentioned as a tip:
http://127.0.0.1:8080/guides/node/prepare-node.html#setting-your-withdrawal-address

This can be closed! @jclapis
