### ISSUE TITLE
http:// in --beacon-rpc-provider flag will throw an error in validator client (Prysm)

### ISSUE THREAD

**Issue by Fluxmux** [rocket-pool/old.docs.rocketpool.net#86]
**Location:**
[Mistake in guide](https://docs.rocketpool.net/guides/node/hybrid.html#setting-the-command-line-arguments-2) with ETH2 client == Prysm
![img](https://user-images.githubusercontent.com/34924583/159078063-04dab88b-f966-4fd3-9cb2-676ef68c5c5f.png)

The validator client cannot connect to the beacon chain client if the protocol (http) is specified in the --beacon-rpc-provider flag.

**Error message:**
`msg="Could not determine if beacon chain started: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused": could not connect"`

**Solution:**
Remove `http://` from `--beacon-rpc-provider http://<your address>:5053`

**Comment by jclapis** [comment]
Fixed with #87.
